# Generated by Django 2.2.2 on 2019-06-14 17:16

from django.db import migrations, models
import markdownx.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Content',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('slug', models.SlugField(max_length=255, unique=True)),
                ('text', markdownx.models.MarkdownxField()),
                ('image_url', models.URLField(blank=True)),
                ('date_created', models.DateField(auto_now_add=True)),
            ],
        ),
    ]
